### ISSUE TITLE
В чём смысл этой конструкции?

### ISSUE THREAD

**Issue by coursar** [AmirSalakhov94/DI#5]
https://github.com/AmirSalakhov94/DI/blob/9dc3bad0600e605b37767cea553ddd0588c54bf5/src/main/java/tech/itpark/di/Container.java#L116-L125

**Comment by AmirSalakhov94** [comment]
Здесь мы проходим по объектам, находим их интерфейсы, если у двух объектов один интерфейс, то кидаем ошибку. Там была неправильная реализация, я поправил.
